#server:
# ssl:
#   enabled: true
#   key-alias: project3-https
#   key-store: classpath:project3.jks.old
#   key-store-type: JKS
#   key-password: password
#   key-store-password: password
#  port: 8080


# ssl:
#   enabled: false
# servlet:
#   session:
#     cookie:
#       same-site: none
#       secure: true

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#    show-sql: true
#  datasource:
#    url: jdbc:h2:mem:memdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#  h2:
#    console.enabled: true
#springdoc:
#  swagger-ui:
#    path: /swagger

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://revatureproject3.c8u1gmouokdn.us-east-1.rds.amazonaws.com/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  # jpa:
  #   hibernate:
  #     ddl-auto: create-drop
    # database-platform: org.hibernate.dialect.H2Dialect
    # defer-datasource-initialization: true
    # show-sql: true
  # datasource:
  #   url: jdbc:h2:mem:memdb
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password: password
  # h2:
  #   console.enabled: true
springdoc:
  swagger-ui:
    path: /swagger
