version: 0.2
phases: 
  build:
    commands:
      - cd social-media-spring-main
      - mvn clean package
artifacts:
  files:
    - social-media-spring-main/Dockerfile
    - social-media-spring-main/target/P3-Back-End.jar
  discard-paths: yes